### ISSUE TITLE
Week6: comments

### ISSUE THREAD

**Issue by parvizi** [3DCloud/Server#46]
You are working hard, and your progress is great. These are my comments on your architecture and codes:
1.  Please complete Server and Client’s Readme files. They should clearly express installation and testing instructions.
2. Clean your repositories. There are some junk folders such as .idea, log, db/migrate, vendor, tmp, and etc ! if they are temporary folders, delete them.
3. Putting credentials on GitHub is a security concern. If it is confidential, you can make a backlog task to hide credentials somehow later.

**Comment by nicoco007** [comment]
1. Will do!
2. `.idea` contains configuration files for opening the project in [RubyMine](https://www.jetbrains.com/ruby/). `db/migrate` contains migrations which are necessary when setting up the project on a new computer or when deploying a new version (they can eventually be combined into the schema once they have been deployed everywhere but are necessary until then). `log`, `vendor`, `tmp`, and all the other folders that have a `.keep` file in them were generated when setting up the Rails project; I'm assuming they're there to avoid issues with permissions but I can check if they're actually necessary if you want.
3. Are you referring to `config/credentials.yml.enc`? If so, that file is meant to be checked in with Git since it contains the encrypted secrets that can only be decrypted with another file called `master.key` (not checked in). I believe it's done that way to simplify changing secrets for testing/production environments among other things.
